server:
  port: 8080
  servlet:
    context-path: /api

# 구글 API KEY
google:
  safeBrowsingApiKey : ${google.api-key}

spring:
  profiles:
    include: key
  mvc:
    async:
      request-timeout: 600000 #600초

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always